// Shared page shell.
//
// Every level/lesson page repeats the same hero block and, for the drill and
// build tracks, the same card scaffold. This script renders those shared parts
// from a small `window.PAGE` config so each page is just its content, not a
// copy of the template.
//
// window.PAGE = {
//   hero: {
//     eyebrow: string,
//     title: string,
//     intro: Array<string | { html: string, class?: string }>,
//     links: Array<{ href: string, label: string }>,
//   },
//   archetype?: "drill" | "build",   // omit for pages with a bespoke body
//   prefix?: string,                 // id prefix used by the matching engine
// }
//
// The hero is rendered into <section class="hero" id="pageHero">. For the drill
// and build archetypes the matching card scaffold is inserted right after it,
// so drill-engine.js / build-engine.js find their prefixed element ids.
//
// GENERATED by tools/generate.mjs from kernel/page-shell/ - do not edit by hand.
// Edit a module in kernel/page-shell/ and re-run the generator instead.
// Shared lesson helpers: the storage seam, escaping, inline markup, progress
// and the output panel. Used by both engines and by the page shell itself.
//
// A self-contained module: window.LessonCommon in the browser, module.exports in Node
// so a unit test can require() it without loading the whole page shell.
(function (root, factory) {
  "use strict";
  var api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.LessonCommon = api;
})(typeof window !== "undefined" ? window : globalThis, function () {
  // Shared lesson helpers used by both engines (build + drill), so the escaping
  // and inline-markup rules live in one place. Defined before any early return
  // below so the engines can rely on it regardless of this page's config.
  // A tiny storage seam so course progress does not hard-depend on localStorage.
  // Defaults to real localStorage; falls back to an in-memory store when it is
  // unavailable (tests, private mode). A page or test can replace
  // LessonCommon.storage before an engine runs to inject its own.
  function memoryStorage() {
    const map = new Map();
    return {
      getItem: (k) => (map.has(k) ? map.get(k) : null),
      setItem: (k, v) => {
        map.set(k, String(v));
      },
      removeItem: (k) => {
        map.delete(k);
      },
    };
  }
  let defaultStorage;
  try {
    defaultStorage = (typeof localStorage !== "undefined" && localStorage) || memoryStorage();
  } catch (e) {
    defaultStorage = memoryStorage();
  }

  const LessonCommon = {
    escapeHtml(s) {
      return String(s)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
    },
    // Turn `backtick` spans into inline <code>, **bold** into <strong>, and
    // [[concept:id|label]] into a clickable concept mention (opens a panel).
    renderInline(text) {
      return (text || "")
        .split(/(\[\[concept:[^\]|]+\|[^\]]+\]\]|`[^`]+`|\*\*[^*]+\*\*)/)
        .map((seg) => {
          const cm = seg.match(/^\[\[concept:([^\]|]+)\|([^\]]+)\]\]$/);
          if (cm)
            return `<button type="button" class="concept-mention" data-concept-id="${LessonCommon.escapeHtml(cm[1])}">${LessonCommon.escapeHtml(cm[2])}</button>`;
          if (seg.length > 1 && seg.startsWith("`") && seg.endsWith("`"))
            return `<code>${LessonCommon.escapeHtml(seg.slice(1, -1))}</code>`;
          if (seg.length > 3 && seg.startsWith("**") && seg.endsWith("**"))
            return `<strong>${LessonCommon.escapeHtml(seg.slice(2, -2))}</strong>`;
          return LessonCommon.escapeHtml(seg);
        })
        .join("");
    },
    // Which card index the URL hash points at, clamped to [0, count - 1].
    cardFromHash(count) {
      const n = parseInt((location.hash || "").replace(/[^0-9]/g, ""), 10);
      return Number.isFinite(n) ? Math.min(Math.max(n - 1, 0), count - 1) : 0;
    },
    // Storage seam (default: localStorage) and the course progress built on it.
    memoryStorage,
    storage: defaultStorage,
    // Course progress (shared XP counter + which cards already paid out), kept
    // behind the storage seam so grading/XP can be unit-tested with a fake store.
    createProgress(opts) {
      const store = (opts && opts.storage) || LessonCommon.storage;
      const xpKey = opts.xpKey;
      const awardedKey = opts.awardedKey;
      const awarded = JSON.parse(store.getItem(awardedKey) || "{}");
      function xp() {
        return parseInt(store.getItem(xpKey) || "0", 10);
      }
      return {
        xp,
        addXP(amount) {
          store.setItem(xpKey, String(xp() + amount));
          return xp();
        },
        isAwarded(i) {
          return Boolean(awarded[i]);
        },
        markAwarded(i) {
          awarded[i] = true;
          store.setItem(awardedKey, JSON.stringify(awarded));
        },
      };
    },
    // The run-output + compile-error surface for a lesson card. Injecting the
    // two elements keeps the show/hide/error logic in one place instead of
    // copied into each engine. Falls back to plain text output when the shared
    // code-lab error panel is unavailable.
    createOutputPanel(els) {
      const output = (els && els.output) || null;
      const errors = (els && els.errors) || null;
      const panel = () =>
        errors && typeof window !== "undefined" && window.CodeLab && window.CodeLab.showErrorPanel
          ? window.CodeLab.showErrorPanel
          : null;
      function showOutput(text, isError) {
        if (!output) return;
        output.hidden = false;
        output.textContent = text;
        output.classList.toggle("is-error", Boolean(isError));
      }
      function hideOutput() {
        if (!output) return;
        output.hidden = true;
        output.textContent = "";
      }
      function clearErrors() {
        const show = panel();
        if (show) show(errors, []);
      }
      function showErrors(list) {
        const show = panel();
        if (show) {
          if (output) output.hidden = true;
          return show(errors, list);
        }
        showOutput((list || []).map((e) => e.friendly || e.raw).join("\n"), true);
        return Boolean(list && list.length);
      }
      return { showOutput, hideOutput, clearErrors, showErrors };
    },
    // Chrome (UI furniture) text lookup: the localized string for the current
    // language from window.ChromeText, else the English fallback when no catalog
    // is active (so non-i18n pages stay byte-identical). key is namespaced
    // (nav.run, card.goal, quiz.check, ...).
    t(key, fallback) {
      var c = (typeof window !== "undefined" && window.ChromeText) || null;
      if (c && Object.prototype.hasOwnProperty.call(c, key)) {
        var v = c[key];
        if (v != null) return v;
      }
      return fallback;
    },
    // Put values into a localized string: "...{expected}..." + { expected: "Woof" }.
    // Named placeholders (not concatenation) so a translator can move the value to
    // wherever the sentence needs it - Spanish rarely keeps English word order.
    // Same {name} convention the code-lab widgets already use, so one syntax is
    // true across every catalog. An unknown placeholder is left visible rather
    // than blanked, so a typo shows up instead of quietly losing text.
    fill(tpl, vars) {
      return String(tpl).replace(/\{(\w+)\}/g, function (m, k) {
        return vars && Object.prototype.hasOwnProperty.call(vars, k) ? String(vars[k]) : m;
      });
    },
  };

  return LessonCommon;
});
// Chrome text helpers: the tHtml/tAttr/tSlot markers a template uses to emit
// localizable static chrome, plus the live repaint that re-applies a language.
//
// A self-contained module: window.PageShellChromeText in the browser, module.exports in Node
// so a unit test can require() it without loading the whole page shell.
(function (root, factory) {
  "use strict";
  if (typeof module === "object" && module.exports) {
    module.exports = factory(require("./lesson-common.js"));
    return;
  }
  var api = factory(root.LessonCommon);
  root.PageShellChromeText = api;
  // The Localizable surface the kernel controller collects, unchanged.
  root.PageShellChrome = { setLocale: api.repaintChrome };
})(typeof window !== "undefined" ? window : globalThis, function (LessonCommon) {
  // Template chrome helpers. With NO catalog (the non-i18n pages) tAttr adds
  // nothing and tHtml/tSlot return the English literal, so the markup is
  // byte-identical; on an i18n page tAttr emits a data-t marker so a live swap can
  // re-localize the element in place.
  function chromeActive() {
    return typeof window !== "undefined" && !!window.ChromeText;
  }
  function tHtml(key, english) {
    return LessonCommon.escapeHtml(LessonCommon.t(key, english));
  }
  function tAttr(key) {
    return chromeActive() ? ' data-t="' + key + '"' : "";
  }
  // A chrome text slot that is NOT already its own element: inactive -> the plain
  // (escaped) English literal, byte-identical; active -> wrapped in <span data-t>
  // so it can be re-localized on a live swap.
  function tSlot(key, english) {
    return chromeActive()
      ? '<span data-t="' + key + '">' + tHtml(key, english) + "</span>"
      : LessonCommon.escapeHtml(english);
  }

  // Chrome Localizable: re-apply the current language to every element carrying a
  // data-t marker (present only on i18n pages). Lets a live language swap
  // re-localize the static chrome (headings, buttons, labels) in place.
  function repaintChrome() {
    if (typeof document === "undefined") return;
    var nodes = document.querySelectorAll("[data-t]");
    for (var i = 0; i < nodes.length; i++) {
      var el = nodes[i];
      el.textContent = LessonCommon.t(el.getAttribute("data-t"), el.textContent);
    }
  }

  return { tHtml: tHtml, tAttr: tAttr, tSlot: tSlot, repaintChrome: repaintChrome };
});
// The two archetype card scaffolds. drillCard is dormant (no live lesson uses
// the drill engine today) but is kept as the base for a future exam track.
//
// A self-contained module: window.PageShellCards in the browser, module.exports in Node
// so a unit test can require() it without loading the whole page shell.
(function (root, factory) {
  "use strict";
  if (typeof module === "object" && module.exports) {
    module.exports = factory(require("./chrome-text.js"));
    return;
  }
  root.PageShellCards = factory(root.PageShellChromeText);
})(typeof window !== "undefined" ? window : globalThis, function (chrome) {
  var tHtml = chrome.tHtml, tAttr = chrome.tAttr, tSlot = chrome.tSlot;

  function drillCard(p) {
    return `
      <section class="card" aria-live="polite">
        <header class="challenge-head">
          <div>
            <p id="${p}Meta" class="meta"></p>
            <h2 id="${p}Title"></h2>
            <p id="${p}Context" class="context"></p>
          </div>
          <div class="badge-group">
            <span id="${p}Concept" class="badge"></span>
            <span id="${p}Progress" class="badge ghost"></span>
          </div>
        </header>

        <section class="pain-box" hidden>
          <h3>The problem</h3>
          <p id="${p}Pain"></p>
        </section>

        <section class="map-box" hidden>
          <h3>Where this fits</h3>
          <p id="${p}Map"></p>
        </section>

        <section id="${p}Quiz" class="quiz-box" hidden>
          <h3>Knowledge check</h3>
          <p id="${p}Question" class="context"></p>
          <div id="${p}Options" class="options"></div>
          <p id="${p}QuizFeedback" class="quiz-feedback" hidden></p>
        </section>

        <div class="code-wrap">
          <pre class="line-numbers"><code id="${p}Code" class="language-csharp"></code></pre>
        </div>
        <div class="code-actions">
          <button id="${p}Run" class="btn" type="button" hidden>Run</button>
        </div>
        <div id="${p}Errors" class="run-errors" hidden></div>
        <pre id="${p}Output" class="run-output" hidden></pre>

        <section class="coach">
          <h3>Goal</h3>
          <ul id="${p}Points" class="coach-list"></ul>
          <div id="${p}Diagram" class="coach-diagram" hidden></div>
        </section>

        <section class="fill-section">
          <h3>Complete the code</h3>
          <div id="${p}Inputs" class="inputs"></div>
        </section>

        <section class="actions">
          <button id="${p}Check" class="btn primary" type="button">Check</button>
          <button id="${p}Hint" class="btn" type="button">Hint</button>
          <button id="${p}Show" class="btn danger" type="button">Show Answer</button>
          <button id="${p}Reset" class="btn" type="button">Reset</button>
        </section>

        <section id="${p}Result" class="result-panel" hidden>
          <h3 id="${p}ResultTitle"></h3>
          <p id="${p}ResultBody"></p>
          <ul id="${p}ResultList"></ul>
        </section>

        <section id="${p}Summary" class="summary-section" hidden>
          <p id="${p}SummaryIntro" class="context"></p>
          <ul id="${p}SummaryList" class="summary-list"></ul>
          <p id="${p}SummaryClose" class="summary-close"></p>
        </section>

        <footer class="nav-row">
          <button id="${p}Prev" class="btn" type="button">Previous</button>
          <button id="${p}Next" class="btn primary" type="button">Next</button>
        </footer>
      </section>`;
  }

  function buildCard(p) {
    return `
      <section class="card" aria-live="polite">
        <header class="challenge-head">
          <div>
            <p id="${p}Meta" class="meta"></p>
            <h2 id="${p}Title"></h2>
            <div id="${p}Context" class="context"></div>
          </div>
          <div class="badge-group">
            <span id="${p}Concept" class="badge"></span>
            <span id="${p}Progress" class="badge ghost"></span>
          </div>
        </header>

        <section id="${p}ExampleWrap" class="example-box" hidden>
          <h3${tAttr("card.pattern")}>${tHtml("card.pattern", "Here's the pattern")}</h3>
          <pre class="code-example"><code id="${p}Example" class="language-csharp"></code></pre>
        </section>

        <section class="coach">
          <h3${tAttr("card.goal")}>${tHtml("card.goal", "Goal")}</h3>
          <ul id="${p}Goal" class="coach-list"></ul>
          <p class="context">
            ${tSlot("card.expected", "Expected output:")} <strong id="${p}Expected" class="expected-line"></strong>
          </p>
        </section>

        <section class="fill-section">
          <h3${tAttr("card.yourcode")}>${tHtml("card.yourcode", "Your Code")}</h3>
          <div id="${p}Editor" class="code-editor-host"></div>
        </section>

        <section class="actions">
          <button id="${p}Run" class="btn primary" type="button">${tHtml("nav.run", "Run")}</button>
          <button id="${p}Solution" class="btn danger" type="button"${tAttr("nav.solution")}>${tHtml("nav.solution", "Show Solution")}</button>
          <button id="${p}Reset" class="btn" type="button"${tAttr("nav.reset")}>${tHtml("nav.reset", "Reset")}</button>
        </section>

        <div id="${p}Errors" class="run-errors" hidden></div>
        <pre id="${p}Output" class="run-output" hidden></pre>

        <section id="${p}Result" class="result-panel" hidden>
          <h3 id="${p}ResultTitle"></h3>
          <p id="${p}ResultBody"></p>
        </section>

        <section id="${p}Summary" class="summary-section" hidden>
          <p id="${p}SummaryIntro" class="context"></p>
          <ul id="${p}SummaryList" class="summary-list"></ul>
          <p id="${p}SummaryClose" class="summary-close"></p>
        </section>

        <footer class="nav-row">
          <button id="${p}Prev" class="btn" type="button"${tAttr("nav.prev")}>${tHtml("nav.prev", "Previous")}</button>
          <button id="${p}Next" class="btn primary" type="button">${tHtml("nav.next", "Next")}</button>
        </footer>
      </section>`;
  }

  return { drillCard: drillCard, buildCard: buildCard };
});
(function () {
  var LessonCommon = window.LessonCommon;
  var chromeText = window.PageShellChromeText;
  var tHtml = chromeText.tHtml, tAttr = chromeText.tAttr, tSlot = chromeText.tSlot;
  var drillCard = window.PageShellCards.drillCard;
  var buildCard = window.PageShellCards.buildCard;

  const page = window.PAGE;
  if (!page) {
    console.error("page-shell: window.PAGE is missing");
    return;
  }

  const hero = document.getElementById("pageHero");
  if (!hero) {
    console.error("page-shell: <section id=\"pageHero\"> is missing");
    return;
  }

  // The hero's intro paragraphs, built from h.intro. Shared by the initial
  // heroHTML render and by repaintHeroIntro (the Localizable swap) so both emit
  // identical markup.
  function heroIntroHTML(h) {
    return (h.intro || [])
      .map((item) => {
        const html = typeof item === "string" ? item : item.html;
        const cls = (typeof item === "object" && item.class) || "subtitle";
        return `<p class="${cls}">${html}</p>`;
      })
      .join("\n");
  }

  function heroHTML(h) {
    const intro = heroIntroHTML(h);
    const links = (h.links || [])
      .map((l) => `<p class="subtitle"><a href="${l.href}">${l.label}</a></p>`)
      .join("\n");
    return `
      <p class="eyebrow">${h.eyebrow}</p>
      <h1>${h.title}</h1>
      ${intro}
      <p class="subtitle"><strong id="courseXpLabel">${tHtml("nav.xp", "Course XP:")} 0</strong></p>
      ${links}`;
  }

  // Localizable content element: repaint the hero's eyebrow, title and intro
  // paragraphs from the (already-refreshed) window.PAGE.hero, in place. Leaves the
  // Course-XP label node, links and agenda untouched - so no cached reference (e.g.
  // the engine's #courseXpLabel) is invalidated. Never runs on the initial render,
  // so the default hero stays byte-identical.
  // The inline (default-language) breadcrumb + document title live in the DOM, not
  // in a bundle - the same snapshot/restore concern the binders have. Delegate to
  // the shared window.ResourceOrigin so switching BACK to the default restores them
  // exactly (bind snapshots each on first sight, restores when resolved is
  // undefined). Never runs on the initial render, so the default stays byte-identical.
  function repaintCrumb(h) {
    let lang = "en";
    try { lang = localStorage.getItem("course_lesson_lang") || "en"; } catch (e) {}
    const metaEl = document.querySelector("p.meta");
    const O = window.ResourceOrigin;
    if (lang === "en") {
      O.bind(document, "title", undefined);
      if (metaEl) O.bind(metaEl, "textContent", undefined);
      return;
    }
    if (h.title) O.bind(document, "title", h.title);
    if (!metaEl || !metaEl.textContent || !h.eyebrow || !h.title) return;
    // The eyebrow reads "<kicker> \u00b7 <part title>"; the breadcrumb wants
    // "<part title> \u00b7 <lesson title>". Reuse the localized pieces already on
    // the page rather than depending on a per-lesson translation.
    const segs = h.eyebrow.split("\u00b7");
    const partTitle = (segs.length > 1 ? segs[segs.length - 1] : segs[0]).trim();
    O.bind(metaEl, "textContent", partTitle + " \u00b7 " + h.title);
  }

  function repaintHero() {
    const h = window.PAGE && window.PAGE.hero;
    if (!h) return;
    const eyebrowEl = hero.querySelector(".eyebrow");
    if (eyebrowEl && h.eyebrow != null) eyebrowEl.textContent = h.eyebrow;
    const h1 = hero.querySelector("h1");
    if (h1 && h.title != null) h1.textContent = h.title;
    // Non-default language only: the breadcrumb + document title were filled from
    // the English registry (not owned by heroHTML), so localize them here. Gated
    // on lang so the default language stays byte-identical.
    repaintCrumb(h);
    const xpLabel = hero.querySelector("#courseXpLabel");
    const anchor = xpLabel ? xpLabel.closest("p") : null;
    if (!anchor || !h1) return;
    // Drop the current intro nodes (everything between <h1> and the XP paragraph).
    let node = h1.nextSibling;
    while (node && node !== anchor) {
      const next = node.nextSibling;
      hero.removeChild(node);
      node = next;
    }
    // Insert fresh intro nodes (identical markup to heroHTML) before the XP p.
    const frag = document.createElement("div");
    frag.innerHTML = heroIntroHTML(h);
    while (frag.firstChild) hero.insertBefore(frag.firstChild, anchor);
  }

  // ---- Concepts: "In this lesson" agenda + click-to-define panel (Phases 2-3) ----
  // Both the agenda chips and in-prose [[concept:...]] mentions carry a
  // data-concept-id; one delegated click handler opens a shared panel that reads
  // the def from window.ConceptIndex (loaded by the lesson page's script block).

  // A ConceptI18n source (voice/lang-aware, graph as fallback) injected by the
  // kernel-controller. Unset (legacy / non-kernel pages) => read the English
  // graph directly, so the default render stays byte-identical.
  let conceptSource = null;
  // The concept currently shown in the panel, kept in a variable (NOT a data-
  // attribute on the panel) so the panel never matches the [data-concept-id] chip
  // selector - otherwise clicking its close button re-triggers showConcept and the
  // panel re-opens (only the outside-click path would then close it).
  let activeConceptId = null;
  function conceptDef(id) {
    if (conceptSource) return { term: conceptSource.term(id), def: conceptSource.def(id) };
    const CI = window.ConceptIndex;
    return (CI && CI.defs && CI.defs[id]) || null;
  }
  function conceptTerm(id) {
    if (conceptSource) return conceptSource.term(id);
    const d = conceptDef(id);
    return d ? d.term : id;
  }
  // Concepts the learner has answered correctly in a checkpoint (written by
  // CodeLab.Quiz to a shared key); used to mark agenda chips as covered.
  function conceptProgress() {
    try {
      return JSON.parse(localStorage.getItem("course_concept_progress") || "{}") || {};
    } catch (e) {
      return {};
    }
  }

  // "In this lesson" - built from the page's own LESSON_META.concepts.
  function renderAgenda() {
    const existing = hero.querySelector(".lesson-agenda");
    if (existing) existing.remove();
    const meta = window.LESSON_META;
    const c = meta && meta.concepts;
    if (!c) return;
    const covered = conceptProgress();
    const ids = (arr) => (arr || []).map((x) => (typeof x === "string" ? x : x.id));
    const groups = [
      { ids: ids(c.introduces), label: tHtml("agenda.new", "New here"), kind: "introduces" },
      { ids: ids(c.revisits), label: tHtml("agenda.revisited", "Revisited"), kind: "revisits" },
      { ids: ids(c.uses), label: tHtml("agenda.used", "Used"), kind: "uses" },
    ].filter((g) => g.ids.length);
    if (!groups.length) return;
    const rows = groups
      .map((g) => {
        const chips = g.ids
          .map(
            (id) =>
              `<button type="button" class="agenda-chip agenda-chip--${g.kind}${covered[id] ? " is-covered" : ""}" data-concept-id="${LessonCommon.escapeHtml(id)}">${LessonCommon.escapeHtml(conceptTerm(id))}</button>`
          )
          .join("");
        return `<div class="agenda-row"><span class="agenda-label">${g.label}</span>${chips}</div>`;
      })
      .join("");
    hero.insertAdjacentHTML(
      "beforeend",
      `<div class="lesson-agenda" aria-label="Concepts in this lesson"><p class="agenda-title">${tHtml("agenda.title", "In this lesson")}</p>${rows}</div>`
    );
  }

  // One shared panel, created on first use, that shows a concept's definition.
  function conceptPanelEl() {
    let el = document.getElementById("conceptPanel");
    if (el) return el;
    el = document.createElement("div");
    el.id = "conceptPanel";
    el.className = "concept-panel";
    el.hidden = true;
    el.innerHTML =
      '<button type="button" class="concept-panel-close" aria-label="Close">\u00d7</button>' +
      '<p class="concept-panel-term"></p><p class="concept-panel-def"></p><p class="concept-panel-link"></p>';
    document.body.appendChild(el);
    el.querySelector(".concept-panel-close").addEventListener("click", () => { el.hidden = true; });
    return el;
  }
  function showConcept(id) {
    const d = conceptDef(id);
    const panel = conceptPanelEl();
    activeConceptId = id;
    panel.querySelector(".concept-panel-term").textContent = d ? d.term : id;
    panel.querySelector(".concept-panel-def").textContent = d ? d.def : LessonCommon.t("concept.notFound", "Definition not found.");
    const prefix = window.LESSON_META && window.LESSON_META.id ? "../../../../" : "";
    panel.querySelector(".concept-panel-link").innerHTML = `<a href="${prefix}glossary.html">${tHtml("concept.openGlossary", "Open the glossary")}</a>`;
    panel.hidden = false;
  }
  document.addEventListener("click", (e) => {
    const btn = e.target && e.target.closest ? e.target.closest("[data-concept-id]") : null;
    if (btn) { showConcept(btn.getAttribute("data-concept-id")); return; }
    const panel = document.getElementById("conceptPanel");
    if (panel && !panel.hidden && !panel.contains(e.target)) panel.hidden = true;
  });

  // Localizable surface: the kernel-controller injects a ConceptI18n source and,
  // on a language swap, calls setLocale() to re-localize the agenda chips + an
  // open panel. Never runs on the default render, so it stays byte-identical.
  window.PageShellConcepts = {
    setConceptSource: function (src) { conceptSource = src; },
    setLocale: function () {
      renderAgenda();
      const panel = document.getElementById("conceptPanel");
      if (panel && !panel.hidden && activeConceptId) showConcept(activeConceptId);
    }
  };

  // Course order lives in generated/course-data.js (window.CourseData). A
  // lesson's final "Next" advances to the next lesson in the same track; a page
  // may still override by setting window.PAGE.nextHref itself. If the course
  // data is not loaded, "Next" simply returns to the index rather than guessing
  // an order here.
  if (!page.nextHref) {
    var href = "index.html";
    var course = window.CourseData || window.Course;
    if (course && typeof course.locate === "function") {
      var current = (location.pathname.split("/").pop() || "").toLowerCase();
      var metaId = window.LESSON_META && window.LESSON_META.id;
      // A migrated page's filename is always "index.html", so its id is the only
      // reliable key - never fall back to locate(current), which would match an
      // arbitrary lesson. A flat legacy page keys on its filename.
      var loc = metaId && typeof course.locateById === "function"
        ? course.locateById(metaId)
        : course.locate(current);
      if (loc && loc.order) {
        href = loc.index < loc.order.length - 1 ? loc.order[loc.index + 1] : "index.html";
      }
    }
    // A generated lesson page lives four dirs deep (content/<track>/<part>/<lesson>/),
    // so a root-relative next href needs the same prefix the page's assets use.
    var rootPrefix = (window.LESSON_META && window.LESSON_META.id) ? "../../../../" : "";
    page.nextHref = rootPrefix + href;
  }

  hero.innerHTML = heroHTML(page.hero);
  renderAgenda();
  // The hero's intro is a Localizable content element (text, no logic); a kernel
  // lesson controller holds this and calls setLocale() on a voice/lang change.
  window.PageShellHero = { setLocale: repaintHero };

  if (page.archetype === "drill") {
    hero.insertAdjacentHTML("afterend", drillCard(page.prefix));
  } else if (page.archetype === "build") {
    hero.insertAdjacentHTML("afterend", buildCard(page.prefix));
  }

})();
