/**
 * tools/generate.mjs - dual-source data pipeline.
 *
 * Order + track/part chrome + baseline lesson fields come from the browser IIFE
 * `course-manifest.js`. `course-registry.js` decides, per lesson id, whether a
 * lesson is still FLAT (registry `path` is null) or has been MIGRATED into a
 * generated `content/<track>/<PP-part>/<LL-lesson>/` directory (registry `path`
 * set). Both are loaded in a Node `vm` sandbox.
 *
 * Emits browser-loadable classic scripts under `generated/`:
 *   - course-data.js   : a frozen `window.CourseData` facade over an inlined
 *                        data literal (adds a stable `id` per lesson). A migrated
 *                        lesson takes its href from the registry (content/.../)
 *                        and its display fields from its own meta.js.
 *   - concept-index.js : `window.ConceptIndex` = { byConcept, byLesson, defs },
 *                        aggregated from every migrated meta.js `concepts` graph
 *                        (stays empty {} while nothing is migrated).
 *
 * For every migrated lesson it also (re)writes that lesson's `index.html` from
 * `templates/lesson.html.tmpl`, wiring the lesson's own meta.js + data.js + the
 * correct engine (or its <id>.viz.js + Prism block) and pointing every shared
 * asset at the fixed `../../../../` prefix (a migrated page lives four dirs deep).
 *
 * Only Node built-ins. Deterministic output (stable key order) so an all-flat
 * run produces byte-identical `generated/` files.
 */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const manifestPath = path.join(root, "course-manifest.js");
const registryPath = path.join(root, "course-registry.js");
const templatePath = path.join(root, "templates", "lesson.html.tmpl");
const generatedDir = path.join(root, "generated");
const courseDataPath = path.join(generatedDir, "course-data.js");
const conceptIndexPath = path.join(generatedDir, "concept-index.js");

const HEADER = "/* GENERATED by tools/generate.mjs from course-manifest.js - do not edit by hand. */";

// Run a course IIFE that assigns `window.<name>` and hand back that global.
function loadBrowserGlobal(file, name) {
  const code = fs.readFileSync(file, "utf8");
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox, { filename: file });
  const value = sandbox.window[name];
  if (!value) throw new Error(`Expected window.${name} after running ${file}`);
  return value;
}

// Run a lesson data/meta file (a pure IIFE that assigns one or more window.*
// globals) and hand back the whole window bag. Used for meta.js (LESSON_META)
// and data.js (BUILD_CONFIG / DRILL_CONFIG - only the prefix is read).
function loadWindowBag(file) {
  const code = fs.readFileSync(file, "utf8");
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox, { filename: file });
  return sandbox.window;
}

// id rule: strip a trailing ".html", else a trailing "/", else use href as-is.
function idFromHref(href) {
  if (href.endsWith(".html")) return href.slice(0, -".html".length);
  if (href.endsWith("/")) return href.slice(0, -1);
  return href;
}

// Registry map: id -> { path, href } (path null while the lesson is still flat).
function loadRegistryMap() {
  const map = new Map();
  try {
    const reg = loadBrowserGlobal(registryPath, "CourseRegistry");
    reg.lessons.forEach(function (l) {
      map.set(l.id, { path: l.path || null, href: l.href });
    });
  } catch (e) {
    // No registry yet -> every lesson is flat.
  }
  return map;
}

// Build a lesson object with a canonical key order, omitting absent optionals,
// so JSON serialization is deterministic. `over` (from a migrated meta) wins
// over the manifest lesson `l` for display fields; href is passed in explicitly.
function projectLesson(l, id, href, over) {
  const m = over || {};
  const pick = function (name) { return m[name] !== undefined ? m[name] : l[name]; };
  const o = {};
  o.id = id;
  o.track = l.track;
  o.part = l.part;
  o.href = href;
  const key = pick("key");
  const total = pick("total");
  if (key !== undefined) o.key = key;
  if (total !== undefined) o.total = total;
  o.title = pick("title");
  o.blurb = pick("blurb");
  o.pill = pick("pill");
  o.time = pick("time");
  o.kind = pick("kind");
  if (l.final !== undefined) o.final = l.final;
  return o;
}

// Walk the manifest in order. For each lesson decide flat vs migrated from the
// registry map; migrated lessons take the registry href + meta display fields
// and are pushed onto `migrated` for index.html emission + concept aggregation.
function projectTracks(tracks, registryMap, migrated) {
  const seenIds = new Set();
  return tracks.map(function (t) {
    return {
      id: t.id,
      name: t.name,
      kicker: t.kicker,
      blurb: t.blurb,
      partPrefix: t.partPrefix,
      parts: t.parts.map(function (p) {
        return {
          track: p.track,
          id: p.id,
          title: p.title,
          kicker: p.kicker,
          lessons: p.lessons.map(function (l) {
            const id = idFromHref(l.href);
            if (seenIds.has(id)) throw new Error("Duplicate lesson id: " + id);
            seenIds.add(id);

            const reg = registryMap.get(id);
            if (!reg || !reg.path) {
              // FLAT: keep the manifest href + manifest fields exactly.
              return projectLesson(l, id, l.href);
            }

            // MIGRATED: load the lesson's own meta.js; href comes from the
            // registry (content/.../), display fields from meta.
            const lessonDir = path.join(root, reg.path);
            const meta = loadWindowBag(path.join(lessonDir, "meta.js")).LESSON_META;
            if (!meta) throw new Error("meta.js for " + id + " did not set window.LESSON_META");
            migrated.push({ id: id, dir: lessonDir, relPath: reg.path, meta: meta });
            return projectLesson(l, id, reg.href, meta);
          })
        };
      })
    };
  });
}

function courseDataFile(data) {
  const json = JSON.stringify(data, null, 2);
  return `${HEADER}
(function (global) {
  var DATA = ${json};

  var trackById = {};
  DATA.tracks.forEach(function (t) {
    t.partById = {};
    t.parts.forEach(function (p) { t.partById[p.id] = p; });
    trackById[t.id] = t;
  });

  function tracks() { return DATA.tracks; }
  function track(id) { return trackById[id]; }

  // Ordered lesson hrefs for a track (parts in order, lessons in order).
  function order(trackId) {
    var t = trackById[trackId], out = [];
    if (!t) return out;
    t.parts.forEach(function (p) {
      p.lessons.forEach(function (l) { out.push(l.href); });
    });
    return out;
  }

  // Ordered lesson objects for a track (parts in order, lessons in order).
  function lessonsOf(trackId) {
    var t = trackById[trackId], out = [];
    if (!t) return out;
    t.parts.forEach(function (p) {
      p.lessons.forEach(function (l) { out.push(l); });
    });
    return out;
  }

  // Which track an href belongs to, its ordered hrefs, and its index within it.
  function locate(href) {
    var target = String(href).toLowerCase();
    for (var i = 0; i < DATA.tracks.length; i++) {
      var ord = order(DATA.tracks[i].id);
      for (var j = 0; j < ord.length; j++) {
        if (ord[j].toLowerCase() === target) {
          return { track: DATA.tracks[i].id, order: ord, index: j };
        }
      }
    }
    return null;
  }

  // Same shape as locate, matched on a lesson's generated id.
  function locateById(id) {
    var target = String(id);
    for (var i = 0; i < DATA.tracks.length; i++) {
      var ls = lessonsOf(DATA.tracks[i].id);
      for (var j = 0; j < ls.length; j++) {
        if (ls[j].id === target) {
          return { track: DATA.tracks[i].id, order: order(DATA.tracks[i].id), index: j };
        }
      }
    }
    return null;
  }

  global.CourseData = Object.freeze({
    tracks: tracks,
    track: track,
    order: order,
    locate: locate,
    locateById: locateById
  });
})(typeof window !== "undefined" ? window : this);
`;
}

// Empty-state output kept byte-identical to the pre-migration scaffold so an
// all-flat run does not churn the file.
const EMPTY_CONCEPT_INDEX = `${HEADER}
(function (global) {
  global.ConceptIndex = Object.freeze({ byConcept: {}, byLesson: {}, defs: {} });
})(typeof window !== "undefined" ? window : this);
`;

// Aggregate every migrated meta.concepts graph into a deterministic index:
//   defs      : conceptId -> { term, def }          (from `introduces`, the owner)
//   byConcept : conceptId -> { introducedBy, revisitedBy[], usedBy[] }
//   byLesson  : lessonId  -> { introduces[], revisits[], uses[] }
function buildConceptIndex(migrated) {
  const defs = {};
  const byConcept = {};
  const byLesson = {};

  function concept(cid) {
    if (!byConcept[cid]) byConcept[cid] = { introducedBy: null, revisitedBy: [], usedBy: [] };
    return byConcept[cid];
  }

  migrated.forEach(function (m) {
    const c = (m.meta && m.meta.concepts) || {};
    const introduces = (c.introduces || []).map(function (x) { return x.id; });
    const revisits = (c.revisits || []).map(function (x) { return x.id; });
    const uses = (c.uses || []).map(function (x) { return x.id; });
    byLesson[m.id] = { introduces: introduces, revisits: revisits, uses: uses };

    (c.introduces || []).forEach(function (x) {
      defs[x.id] = { term: x.term, def: x.def };
      concept(x.id).introducedBy = m.id;
    });
    revisits.forEach(function (cid) { concept(cid).revisitedBy.push(m.id); });
    uses.forEach(function (cid) { concept(cid).usedBy.push(m.id); });
  });

  return { byConcept: sortKeys(byConcept), byLesson: sortKeys(byLesson), defs: sortKeys(defs) };
}

// Return a new object with keys in sorted order (deterministic serialization).
function sortKeys(obj) {
  const out = {};
  Object.keys(obj).sort().forEach(function (k) { out[k] = obj[k]; });
  return out;
}

function conceptIndexFile(index) {
  const empty =
    !Object.keys(index.byConcept).length &&
    !Object.keys(index.byLesson).length &&
    !Object.keys(index.defs).length;
  if (empty) return EMPTY_CONCEPT_INDEX;
  const json = JSON.stringify(index, null, 2);
  return `${HEADER}
(function (global) {
  global.ConceptIndex = Object.freeze(${json});
})(typeof window !== "undefined" ? window : this);
`;
}

// ---- index.html emission from templates/lesson.html.tmpl ----

function htmlEscape(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Escape a value for embedding inside a double-quoted JS string literal.
function jsInner(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

// The four template variants, in file order: build, drill, viz, checkpoint.
function loadTemplateVariants() {
  const tmpl = fs.readFileSync(templatePath, "utf8");
  const blocks = tmpl.match(/<!doctype html>[\s\S]*?<\/html>/gi);
  if (!blocks || blocks.length < 4) throw new Error("Expected 4 variants in lesson.html.tmpl");
  return { build: blocks[0], drill: blocks[1], viz: blocks[2], checkpoint: blocks[3] };
}

// Read a build/drill lesson's element-id prefix from its data.js config global.
function prefixFromData(dir) {
  const bag = loadWindowBag(path.join(dir, "data.js"));
  const cfg = bag.BUILD_CONFIG || bag.DRILL_CONFIG;
  if (!cfg || !cfg.prefix) throw new Error("data.js in " + dir + " has no BUILD_CONFIG/DRILL_CONFIG prefix");
  return cfg.prefix;
}

// Render a migrated lesson's index.html from the matching template variant.
function renderIndexHtml(m, variants) {
  const meta = m.meta;
  const archetype = meta.archetype;
  let html = variants[archetype];
  if (!html) throw new Error("Unknown archetype '" + archetype + "' for lesson " + m.id);

  html = html
    .replace(/\{\{DOC_TITLE\}\}/g, htmlEscape(meta.docTitle))
    .replace(/\{\{EYEBROW\}\}/g, jsInner(meta.eyebrow))
    .replace(/\{\{TITLE\}\}/g, jsInner(meta.title))
    .replace(/\{\{INTRO\}\}/g, JSON.stringify(meta.intro || []))
    .replace(/\{\{META_SRC\}\}/g, "meta.js")
    .replace(/\{\{DATA_SRC\}\}/g, "data.js")
    .replace(/\{\{VIZ_SRC\}\}/g, m.id + ".viz.js");

  if (archetype === "build" || archetype === "drill") {
    const enginePath = "../../../../" + (meta.engine === "drill" ? "drill-engine.js" : "build-engine.js");
    html = html.replace(/\{\{ENGINE_SRC\}\}/g, enginePath);
    // The card scaffold needs the same element-id prefix the engine reads from
    // its config; page-shell picks it up from window.PAGE.prefix.
    const prefix = prefixFromData(m.dir);
    html = html.replace(
      new RegExp('archetype: "' + archetype + '",'),
      'archetype: "' + archetype + '",\n          prefix: ' + JSON.stringify(prefix) + ','
    );
  }

  // A generated page reads the built course data, never the raw manifest.
  html = html.replace(/\.\.\/\.\.\/\.\.\/\.\.\/course-manifest\.js/g, "../../../../generated/course-data.js");
  return html;
}

function main() {
  // `--out <dir>` writes ONLY the two generated data files into <dir> and skips
  // the per-lesson index.html emission - used by the drift guard to compare
  // against the committed generated/ without touching any real file.
  const argv = process.argv.slice(2);
  const outIdx = argv.indexOf("--out");
  const outDir = outIdx >= 0 ? path.resolve(argv[outIdx + 1] || "") : null;

  const Course = loadBrowserGlobal(manifestPath, "Course");
  const registryMap = loadRegistryMap();
  const migrated = [];
  const data = { tracks: projectTracks(Course.tracks(), registryMap, migrated) };

  const targetDir = outDir || generatedDir;
  fs.mkdirSync(targetDir, { recursive: true });
  fs.writeFileSync(path.join(targetDir, "course-data.js"), courseDataFile(data));
  fs.writeFileSync(path.join(targetDir, "concept-index.js"), conceptIndexFile(buildConceptIndex(migrated)));

  // Emit each migrated lesson's index.html (deterministic manifest order).
  // Skipped under --out so a drift check never rewrites content/ pages.
  if (!outDir) {
    let variants = null;
    migrated.forEach(function (m) {
      if (!variants) variants = loadTemplateVariants();
      const html = renderIndexHtml(m, variants);
      fs.writeFileSync(path.join(m.dir, "index.html"), html);
    });
  }

  const lessonCount = data.tracks.reduce(function (n, t) {
    return n + t.parts.reduce(function (m, p) { return m + p.lessons.length; }, 0);
  }, 0);

  console.log(`Wrote course-data.js and concept-index.js to ${path.relative(root, targetDir) || "."}${outDir ? " (--out)" : ""}`);
  console.log(`Lessons: ${lessonCount} across ${data.tracks.length} tracks; migrated: ${migrated.length}`);
}

main();
