/**
 * tools/generate.mjs - the course-data pipeline. `course-registry.js` is the
 * single source of the course path: `tracks[]` gives the track + part chrome and
 * order, `lessons[]` gives the lessons in reading order. A migrated lesson's
 * display fields come from its own `content/.../meta.js`. Loaded in a Node `vm`
 * sandbox.
 *
 * Emits browser-loadable classic scripts under `generated/`:
 *   - course-data.js   : a frozen `window.CourseData` facade over an inlined data
 *                        literal (adds a stable `id` per lesson).
 *   - concept-index.js : `window.ConceptIndex` = { byConcept, byLesson, defs },
 *                        aggregated from every migrated meta.js `concepts` graph.
 *
 * For every migrated lesson it also (re)writes that lesson's `index.html` from
 * `templates/lesson.html.tmpl`, wiring the lesson's own meta.js + data.js + the
 * correct engine (or its <id>.viz.js + Prism block) and pointing every shared
 * asset at the fixed `../../../../` prefix (a migrated page lives four dirs deep).
 *
 * `--out <dir>` mirrors ALL generated output under <dir> (the two data files plus
 * each lesson's index.html at <dir>/<relPath>/index.html) and touches nothing in
 * the real tree - the drift guard uses it to diff a fresh build against commit.
 *
 * Only Node built-ins. Deterministic output (stable key order).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadBrowserGlobal, loadWindowBag, idFromHref } from "./lib.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const registryPath = path.join(root, "course-registry.js");
const templatePath = path.join(root, "templates", "lesson.html.tmpl");
const generatedDir = path.join(root, "generated");
const courseDataPath = path.join(generatedDir, "course-data.js");
const conceptIndexPath = path.join(generatedDir, "concept-index.js");

const HEADER = "/* GENERATED by tools/generate.mjs from course-registry.js - do not edit by hand. */";

// Part kicker ("Part one/two/...") is derived from the track partPrefix + the
// part's 1-based position (ORDINALS[1] = "one").
const ORDINALS = ["", "one", "two", "three", "four", "five", "six", "seven",
  "eight", "nine", "ten", "eleven", "twelve"];

// Localized ordinals for the derived part kicker (partPrefix + ordinal). Keyed by
// language; a language only needs an entry if its tracks carry an i18n partPrefix.
const ORDINALS_I18N = {
  es: ["", "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho",
    "nueve", "diez", "once", "doce"]
};

// Build a lesson card with a canonical key order, omitting absent optionals, so
// JSON serialization is deterministic. Display fields come from the lesson's
// meta.js.
function projectLesson(id, line, meta) {
  const src = meta;
  const o = {};
  o.id = id;
  o.track = line.track;
  o.part = line.part;
  o.href = line.href;
  if (src.key !== undefined) o.key = src.key;
  if (src.total !== undefined) o.total = src.total;
  o.title = src.title;
  o.blurb = src.blurb;
  o.pill = src.pill;
  o.time = src.time;
  o.kind = "lesson";
  return o;
}

// Walk the registry: tracks[] carries the track + part chrome (and order),
// lessons[] the lessons in reading order. Each part's kicker is rebuilt from the
// track partPrefix + its position. Each lesson loads its meta.js and is pushed
// onto `migrated` for index.html + concept aggregation.
function projectTracks(registry, migrated) {
  const seenIds = new Set();
  const lessonsIn = function (trackId, partId) {
    return registry.lessons.filter(function (l) { return l.track === trackId && l.part === partId; });
  };
  return registry.tracks.map(function (t) {
    if (!Array.isArray(t.parts)) throw new Error("track \"" + t.id + "\" has no parts[] (registry mid-edit?)");
    return {
      id: t.id,
      name: t.name,
      kicker: t.kicker,
      blurb: t.blurb,
      partPrefix: t.partPrefix,
      parts: t.parts.map(function (p, pi) {
        return {
          track: t.id,
          id: p.id,
          title: p.title,
          kicker: t.partPrefix + (ORDINALS[pi + 1] || String(pi + 1)),
          lessons: lessonsIn(t.id, p.id).map(function (l) {
            const id = l.id || idFromHref(l.href);
            if (seenIds.has(id)) throw new Error("Duplicate lesson id: " + id);
            seenIds.add(id);

            // meta.js is the source. `l.path` is a repo-controlled registry
            // field (never untrusted input), safe to join onto root.
            if (!l.path) throw new Error("registry line for " + id + " has no content path");
            const lessonDir = path.join(root, l.path);
            const meta = loadWindowBag(path.join(lessonDir, "meta.js")).LESSON_META;
            if (!meta) throw new Error("meta.js for " + id + " did not set window.LESSON_META");
            migrated.push({ id: id, dir: lessonDir, relPath: l.path, meta: meta });
            return projectLesson(id, l, meta);
          })
        };
      })
    };
  });
}

function courseDataFile(data) {
  const json = JSON.stringify(data, null, 2);
  return `${HEADER}
(function (global) {
  var DATA = ${json};

  var trackById = {};
  DATA.tracks.forEach(function (t) {
    t.partById = {};
    t.parts.forEach(function (p) { t.partById[p.id] = p; });
    trackById[t.id] = t;
  });

  function tracks() { return DATA.tracks; }
  function track(id) { return trackById[id]; }

  // Ordered lesson hrefs for a track (parts in order, lessons in order).
  function order(trackId) {
    var t = trackById[trackId], out = [];
    if (!t) return out;
    t.parts.forEach(function (p) {
      p.lessons.forEach(function (l) { out.push(l.href); });
    });
    return out;
  }

  // Ordered lesson objects for a track (parts in order, lessons in order).
  function lessonsOf(trackId) {
    var t = trackById[trackId], out = [];
    if (!t) return out;
    t.parts.forEach(function (p) {
      p.lessons.forEach(function (l) { out.push(l); });
    });
    return out;
  }

  // Which track an href belongs to, its ordered hrefs, and its index within it.
  function locate(href) {
    var target = String(href).toLowerCase();
    for (var i = 0; i < DATA.tracks.length; i++) {
      var ord = order(DATA.tracks[i].id);
      for (var j = 0; j < ord.length; j++) {
        if (ord[j].toLowerCase() === target) {
          return { track: DATA.tracks[i].id, order: ord, index: j };
        }
      }
    }
    return null;
  }

  // Same shape as locate, matched on a lesson's generated id.
  function locateById(id) {
    var target = String(id);
    for (var i = 0; i < DATA.tracks.length; i++) {
      var ls = lessonsOf(DATA.tracks[i].id);
      for (var j = 0; j < ls.length; j++) {
        if (ls[j].id === target) {
          return { track: DATA.tracks[i].id, order: order(DATA.tracks[i].id), index: j };
        }
      }
    }
    return null;
  }

  global.CourseData = Object.freeze({
    tracks: tracks,
    track: track,
    order: order,
    locate: locate,
    locateById: locateById
  });
})(typeof window !== "undefined" ? window : this);
`;
}

// Empty-state output kept byte-identical to the pre-migration scaffold so an
// all-flat run does not churn the file.
const EMPTY_CONCEPT_INDEX = `${HEADER}
(function (global) {
  global.ConceptIndex = Object.freeze({ byConcept: {}, byLesson: {}, defs: {} });
})(typeof window !== "undefined" ? window : this);
`;

// Aggregate every migrated meta.concepts graph into a deterministic index:
//   defs      : conceptId -> { term, def }          (from `introduces`, the owner)
//   byConcept : conceptId -> { introducedBy, revisitedBy[], usedBy[] }
//   byLesson  : lessonId  -> { introduces[], revisits[], uses[] }
function buildConceptIndex(migrated) {
  const defs = {};
  const byConcept = {};
  const byLesson = {};

  // Concept term/def now live in the lesson's English resource bundle
  // (concept.<id>.term / concept.<id>.def), not meta.js. Read them back here so
  // the index stays the single derived registry.
  function conceptTextFor(dir) {
    let bag;
    try { bag = JSON.parse(fs.readFileSync(path.join(dir, "res", "strings", "default", "en.json"), "utf8")); }
    catch (e) { return {}; }
    const out = {};
    Object.keys(bag).forEach(function (k) {
      const mm = /^concept\.(.+)\.(term|def)$/.exec(k);
      if (mm) { (out[mm[1]] = out[mm[1]] || {})[mm[2]] = bag[k]; }
    });
    return out;
  }

  function concept(cid) {
    if (!byConcept[cid]) byConcept[cid] = { introducedBy: null, revisitedBy: [], usedBy: [] };
    return byConcept[cid];
  }

  migrated.forEach(function (m) {
    const c = (m.meta && m.meta.concepts) || {};
    const text = conceptTextFor(m.dir);
    const introduces = (c.introduces || []).map(function (x) { return x.id; });
    const revisits = (c.revisits || []).map(function (x) { return x.id; });
    const uses = (c.uses || []).map(function (x) { return x.id; });
    byLesson[m.id] = { introduces: introduces, revisits: revisits, uses: uses };

    (c.introduces || []).forEach(function (x) {
      const t = text[x.id] || {};
      defs[x.id] = { term: t.term, def: t.def };
      concept(x.id).introducedBy = m.id;
    });
    revisits.forEach(function (cid) { concept(cid).revisitedBy.push(m.id); });
    uses.forEach(function (cid) { concept(cid).usedBy.push(m.id); });
  });

  return { byConcept: sortKeys(byConcept), byLesson: sortKeys(byLesson), defs: sortKeys(defs) };
}

// Return a new object with keys in sorted order (deterministic serialization).
function sortKeys(obj) {
  const out = {};
  Object.keys(obj).sort().forEach(function (k) { out[k] = obj[k]; });
  return out;
}

function conceptIndexFile(index) {
  const empty =
    !Object.keys(index.byConcept).length &&
    !Object.keys(index.byLesson).length &&
    !Object.keys(index.defs).length;
  if (empty) return EMPTY_CONCEPT_INDEX;
  const json = JSON.stringify(index, null, 2);
  return `${HEADER}
(function (global) {
  global.ConceptIndex = Object.freeze(${json});
})(typeof window !== "undefined" ? window : this);
`;
}

// Aggregate non-base concept text (concept.<id>.term/.def in each lesson's
// res/strings/<voice>/<lang>.json, excluding the English base default/en) into
// per-language overlay maps: lang -> { voice: { id: { term?, def? } } }. English
// stays in concept-index.js; only translations are emitted here.
function buildConceptI18n(migrated) {
  const byLang = {};
  const KEY = /^concept\.(.+)\.(term|def)$/;
  migrated.forEach(function (m) {
    const stringsDir = path.join(m.dir, "res", "strings");
    let voiceDirs;
    try { voiceDirs = fs.readdirSync(stringsDir); } catch (e) { return; }
    voiceDirs.forEach(function (voice) {
      let files;
      try { files = fs.readdirSync(path.join(stringsDir, voice)); } catch (e) { return; }
      files.forEach(function (file) {
        const lm = /^(.+)\.json$/.exec(file);
        if (!lm) return;
        const lang = lm[1];
        if (voice === "default" && lang === "en") return; // the English base lives in the graph
        let bag;
        try { bag = JSON.parse(fs.readFileSync(path.join(stringsDir, voice, file), "utf8")); } catch (e) { return; }
        Object.keys(bag).forEach(function (k) {
          const mm = KEY.exec(k);
          if (!mm) return;
          const v = ((byLang[lang] = byLang[lang] || {})[voice] = byLang[lang][voice] || {});
          (v[mm[1]] = v[mm[1]] || {})[mm[2]] = bag[k];
        });
      });
    });
  });
  return byLang;
}

// Deterministic deep key sort so the emitted overlay never churns spuriously.
function sortDeep(v) {
  if (Array.isArray(v)) return v.map(sortDeep);
  if (v && typeof v === "object") {
    const out = {};
    Object.keys(v).sort().forEach(function (k) { out[k] = sortDeep(v[k]); });
    return out;
  }
  return v;
}

function conceptI18nFile(lang, byVoice) {
  const json = JSON.stringify(sortDeep(byVoice), null, 2);
  return `${HEADER}
(function (global) {
  global.ConceptI18nData = global.ConceptI18nData || {};
  global.ConceptI18nData[${JSON.stringify(lang)}] = ${json};
})(typeof window !== "undefined" ? window : this);
`;
}

// Assemble the landing overlay per language from BOTH sources of translation:
// the track/part CHROME (registry i18n blocks) and each lesson's CARD text
// (card.title/card.blurb in its res/strings/default/<lang>.json). The shape mirrors
// exactly what course-index.js consumes as window.LandingContent:
//   { tracks:{id:{name,kicker,blurb}}, parts:{EnglishTitle:esTitle},
//     partKickers:{EnglishKicker:esKicker}, lessons:{id:{title,blurb}} }.
// The part kicker is DERIVED (partPrefix + localized ordinal), never hand-written.
function buildLandingI18n(registry, migrated) {
  const langs = new Set();
  registry.tracks.forEach(function (t) {
    Object.keys(t.i18n || {}).forEach(function (l) { langs.add(l); });
    (t.parts || []).forEach(function (p) {
      Object.keys(p.i18n || {}).forEach(function (l) { langs.add(l); });
    });
  });

  // Lesson card text by language: lang -> { id -> { title?, blurb? } }. Only the
  // default voice carries a lesson's card title/blurb; English is never overlaid.
  const cardByLang = {};
  migrated.forEach(function (m) {
    const voiceDir = path.join(m.dir, "res", "strings", "default");
    let files;
    try { files = fs.readdirSync(voiceDir); } catch (e) { return; }
    files.forEach(function (file) {
      const lm = /^(.+)\.json$/.exec(file);
      if (!lm) return;
      const lang = lm[1];
      if (lang === "en") return;
      let bag;
      try { bag = JSON.parse(fs.readFileSync(path.join(voiceDir, file), "utf8")); } catch (e) { return; }
      const card = {};
      if (typeof bag["card.title"] === "string") card.title = bag["card.title"];
      if (typeof bag["card.blurb"] === "string") card.blurb = bag["card.blurb"];
      if (Object.keys(card).length) {
        langs.add(lang);
        (cardByLang[lang] = cardByLang[lang] || {})[m.id] = card;
      }
    });
  });

  const out = {};
  langs.forEach(function (lang) {
    const overlay = { tracks: {}, parts: {}, partKickers: {}, lessons: {} };
    const ordinals = ORDINALS_I18N[lang] || [];
    registry.tracks.forEach(function (t) {
      const ti = (t.i18n || {})[lang];
      if (ti) {
        const tr = {};
        if (ti.name != null) tr.name = ti.name;
        if (ti.kicker != null) tr.kicker = ti.kicker;
        if (ti.blurb != null) tr.blurb = ti.blurb;
        if (Object.keys(tr).length) overlay.tracks[t.id] = tr;
      }
      const prefixLoc = ti && ti.partPrefix;
      (t.parts || []).forEach(function (p, pi) {
        const pTitle = (p.i18n || {})[lang] && p.i18n[lang].title;
        if (pTitle != null) overlay.parts[p.title] = pTitle;
        if (prefixLoc != null && ordinals[pi + 1]) {
          const enKicker = t.partPrefix + (ORDINALS[pi + 1] || String(pi + 1));
          overlay.partKickers[enKicker] = prefixLoc + ordinals[pi + 1];
        }
      });
    });
    Object.keys(cardByLang[lang] || {}).forEach(function (id) {
      overlay.lessons[id] = cardByLang[lang][id];
    });
    out[lang] = overlay;
  });
  return out;
}

function landingI18nFile(overlay) {
  return JSON.stringify(sortDeep(overlay), null, 2) + "\n";
}

// ---- index.html emission from templates/lesson.html.tmpl ----

function htmlEscape(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Escape a value for embedding inside a double-quoted JS string literal.
function jsInner(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

// The four template variants, in file order: build, drill, viz, checkpoint.
function loadTemplateVariants() {
  const tmpl = fs.readFileSync(templatePath, "utf8");
  const blocks = tmpl.match(/<!doctype html>[\s\S]*?<\/html>/gi);
  if (!blocks || blocks.length < 4) throw new Error("Expected 4 variants in lesson.html.tmpl");
  return { build: blocks[0], drill: blocks[1], viz: blocks[2], checkpoint: blocks[3] };
}

// Read a build/drill lesson's element-id prefix from its data.js config global.
function prefixFromData(dir) {
  const bag = loadWindowBag(path.join(dir, "data.js"));
  const cfg = bag.BUILD_CONFIG || bag.DRILL_CONFIG;
  if (!cfg || !cfg.prefix) throw new Error("data.js in " + dir + " has no BUILD_CONFIG/DRILL_CONFIG prefix");
  return cfg.prefix;
}

// Render a migrated lesson's index.html from the matching template variant.
function renderIndexHtml(m, variants) {
  const meta = m.meta;
  const archetype = meta.archetype;
  let html = variants[archetype];
  if (!html) throw new Error("Unknown archetype '" + archetype + "' for lesson " + m.id);

  html = html
    .replace(/\{\{DOC_TITLE\}\}/g, htmlEscape(meta.docTitle))
    .replace(/\{\{EYEBROW\}\}/g, jsInner(meta.eyebrow))
    .replace(/\{\{TITLE\}\}/g, jsInner(meta.title))
    .replace(/\{\{INTRO\}\}/g, JSON.stringify(meta.intro || []))
    .replace(/\{\{META_SRC\}\}/g, "meta.js")
    .replace(/\{\{DATA_SRC\}\}/g, "data.js")
    .replace(/\{\{VIZ_SRC\}\}/g, m.id + ".viz.js");

  if (archetype === "build" || archetype === "drill") {
    const enginePath = "../../../../" + (meta.engine === "drill" ? "drill-engine.js" : "build-engine.js");
    html = html.replace(/\{\{ENGINE_SRC\}\}/g, enginePath);
    // The card scaffold needs the same element-id prefix the engine reads from
    // its config; page-shell picks it up from window.PAGE.prefix. Match the real
    // `archetype:` property line (leading newline + its own indentation) and add
    // the prefix line at the same indent, so the injection stays aligned and
    // cannot latch onto the literal appearing anywhere else in the page.
    const prefix = prefixFromData(m.dir);
    html = html.replace(
      new RegExp('(\\n([ \\t]*)archetype: "' + archetype + '",)'),
      '$1\n$2prefix: ' + JSON.stringify(prefix) + ','
    );

    // Opt-in resource layer: when meta.resources is set, the lesson's teaching
    // prose lives in res/strings/<voice>/<lang>.json instead of inline in
    // data.js. Swap the static `page-shell + engine` tail for the resource
    // modules + bootstrap, which apply the selected voice's strings onto the
    // lesson globals and then inject the (unchanged) page-shell and engine.
    if (meta.resources) {
      // runtime:"kernel" swaps the reload-on-change bootstrap for the live-swap
      // kernel controller; it supersedes the plain resource tail (never both).
      const controller = meta.runtime === "kernel" ? "kernel-controller" : "bootstrap";
      html = applyResourceTail(html, meta.resources, enginePath, m.id, controller);
    }
  } else if (archetype === "viz" && meta.resources) {
    // A viz lesson's teaching prose (hero + step narrations + legend labels) can
    // live in res/strings too; the binder is bind-viz and there is no engine.
    const controller = meta.runtime === "kernel" ? "kernel-controller" : "bootstrap";
    html = applyResourceTailViz(html, meta.resources, m.id, controller);
  } else if (archetype === "checkpoint" && meta.resources) {
    // A checkpoint lesson's prose (hero + quiz title/intro + question stems,
    // options and explanations) can live in res/strings; the binder is
    // bind-checkpoint and there is no engine (the Quiz is a code-lab widget).
    const controller = meta.runtime === "kernel" ? "kernel-controller" : "bootstrap";
    html = applyResourceTailCheckpoint(html, meta.resources, m.id, controller);
  }

  return html;
}

// Rewrite the static `page-shell + data + engine` tail into the resource-gated
// tail. page-shell.js and the engine are no longer loaded statically; the
// bootstrap injects them after applying the chosen voice's strings, so both
// engines stay byte-for-byte the files the flat pages use.
function applyResourceTail(html, resources, enginePath, lessonId, controllerModule = "bootstrap") {
  const base = resources.base || "res/strings";
  const lang = resources.lang || "en";
  const langs = (resources.langs && resources.langs.length ? resources.langs : [lang]).join(",");
  const voices = (resources.voices || ["default"]).join(",");

  const staticTail =
    '    <script src="../../../../page-shell.js"></script>\n' +
    '    <script src="data.js"></script>\n' +
    '    <script src="' + enginePath + '"></script>';
  if (html.indexOf(staticTail) === -1) {
    throw new Error("resource wiring: could not find the static engine tail for " + lessonId);
  }

  const modules = ["resolver", "store", "manager", "settings", "preference", "theme-section", "voice-section", "lang-section", "concept-i18n", "bind-build"]
    .map((mod) => '    <script src="../../../../resource/' + mod + '.js"></script>')
    .join("\n");
  const resourceTail =
    '    <script src="data.js"></script>\n' +
    modules + "\n" +
    '    <script\n' +
    '      src="../../../../resource/' + controllerModule + '.js"\n' +
    '      data-page-shell="../../../../page-shell.js"\n' +
    '      data-engine="' + enginePath + '"\n' +
    '      data-res-base="' + base + '"\n' +
    '      data-res-lang="' + lang + '"\n' +
    '      data-res-langs="' + langs + '"\n' +
    '      data-res-voices="' + voices + '"\n' +
    '    ></script>';

  return html.replace(staticTail, resourceTail);
}

// Viz variant of the resource tail. A viz page has no data.js and no engine: its
// visual (window.LESSON_VIZ, set by <id>.viz.js) is mounted by page-shell. So we
// swap only the trailing static page-shell.js load for the resource modules (with
// bind-viz, not bind-build) + the controller; the controller injects page-shell
// after binding. No data-engine.
function applyResourceTailViz(html, resources, lessonId, controllerModule = "bootstrap") {
  const base = resources.base || "res/strings";
  const lang = resources.lang || "en";
  const langs = (resources.langs && resources.langs.length ? resources.langs : [lang]).join(",");
  const voices = (resources.voices || ["default"]).join(",");

  const staticTail = '    <script src="../../../../page-shell.js"></script>';
  if (html.indexOf(staticTail) === -1) {
    throw new Error("viz resource wiring: could not find the static page-shell tail for " + lessonId);
  }

  const modules = ["resolver", "store", "manager", "settings", "preference", "theme-section", "voice-section", "lang-section", "concept-i18n", "bind-viz"]
    .map((mod) => '    <script src="../../../../resource/' + mod + '.js"></script>')
    .join("\n");
  const resourceTail =
    modules + "\n" +
    '    <script\n' +
    '      src="../../../../resource/' + controllerModule + '.js"\n' +
    '      data-page-shell="../../../../page-shell.js"\n' +
    '      data-res-base="' + base + '"\n' +
    '      data-res-lang="' + lang + '"\n' +
    '      data-res-langs="' + langs + '"\n' +
    '      data-res-voices="' + voices + '"\n' +
    '    ></script>';

  return html.replace(staticTail, resourceTail);
}

// Checkpoint variant of the resource tail. Like viz, a checkpoint page mounts its
// widget (the code-lab Quiz, from window.QUIZ_CONFIG in data.js) via page-shell,
// with no engine. data.js is already loaded ahead of the tail, so we swap only
// the trailing static page-shell.js load for the resource modules (with
// bind-checkpoint) + the controller, which injects page-shell after binding.
function applyResourceTailCheckpoint(html, resources, lessonId, controllerModule = "bootstrap") {
  const base = resources.base || "res/strings";
  const lang = resources.lang || "en";
  const langs = (resources.langs && resources.langs.length ? resources.langs : [lang]).join(",");
  const voices = (resources.voices || ["default"]).join(",");

  const staticTail = '    <script src="../../../../page-shell.js"></script>';
  if (html.indexOf(staticTail) === -1) {
    throw new Error("checkpoint resource wiring: could not find the static page-shell tail for " + lessonId);
  }

  const modules = ["resolver", "store", "manager", "settings", "preference", "theme-section", "voice-section", "lang-section", "concept-i18n", "bind-checkpoint"]
    .map((mod) => '    <script src="../../../../resource/' + mod + '.js"></script>')
    .join("\n");
  const resourceTail =
    modules + "\n" +
    '    <script\n' +
    '      src="../../../../resource/' + controllerModule + '.js"\n' +
    '      data-page-shell="../../../../page-shell.js"\n' +
    '      data-res-base="' + base + '"\n' +
    '      data-res-lang="' + lang + '"\n' +
    '      data-res-langs="' + langs + '"\n' +
    '      data-res-voices="' + voices + '"\n' +
    '    ></script>';

  return html.replace(staticTail, resourceTail);
}

function main() {
  // `--out <dir>` mirrors every generated artefact under <dir> instead of writing
  // in place: the two data files at <dir>/course-data.js + <dir>/concept-index.js
  // and each migrated lesson's page at <dir>/<relPath>/index.html. Nothing in the
  // real generated/ or content/ is touched - the drift guard diffs a fresh build
  // (data files AND pages) against what is committed.
  const argv = process.argv.slice(2);
  const outIdx = argv.indexOf("--out");
  const outDir = outIdx >= 0 ? path.resolve(argv[outIdx + 1] || "") : null;

  const registry = loadBrowserGlobal(registryPath, "CourseRegistry");
  const migrated = [];
  const data = { tracks: projectTracks(registry, migrated) };

  const dataDir = outDir || generatedDir;
  fs.mkdirSync(dataDir, { recursive: true });
  fs.writeFileSync(path.join(dataDir, "course-data.js"), courseDataFile(data));
  fs.writeFileSync(path.join(dataDir, "concept-index.js"), conceptIndexFile(buildConceptIndex(migrated)));

  // Per-language concept text overlays (empty until translations exist). Remove
  // stale files so deleting a language's text also removes its overlay.
  const conceptI18n = buildConceptI18n(migrated);
  fs.readdirSync(dataDir)
    .filter(function (f) { return /^concept-i18n\..+\.js$/.test(f); })
    .forEach(function (f) {
      const lang = f.slice("concept-i18n.".length, -".js".length);
      if (!conceptI18n[lang]) fs.unlinkSync(path.join(dataDir, f));
    });
  Object.keys(conceptI18n).sort().forEach(function (lang) {
    fs.writeFileSync(path.join(dataDir, "concept-i18n." + lang + ".js"), conceptI18nFile(lang, conceptI18n[lang]));
  });

  // Landing overlay per language (chrome from the registry i18n blocks + cards from
  // each lesson's own es.json). Remove stale files so dropping a language cleans up.
  const landingI18n = buildLandingI18n(registry, migrated);
  fs.readdirSync(dataDir)
    .filter(function (f) { return /^landing-i18n\..+\.json$/.test(f); })
    .forEach(function (f) {
      const lang = f.slice("landing-i18n.".length, -".json".length);
      if (!landingI18n[lang]) fs.unlinkSync(path.join(dataDir, f));
    });
  Object.keys(landingI18n).sort().forEach(function (lang) {
    fs.writeFileSync(path.join(dataDir, "landing-i18n." + lang + ".json"), landingI18nFile(landingI18n[lang]));
  });

  // Emit each migrated lesson's index.html (deterministic registry order). Under
  // --out these go to <outDir>/<relPath>/index.html (a scratch mirror) so the
  // drift guard can diff them without rewriting the real content/ pages.
  let variants = null;
  migrated.forEach(function (m) {
    if (!variants) variants = loadTemplateVariants();
    const html = renderIndexHtml(m, variants);
    const dest = outDir ? path.join(outDir, m.relPath, "index.html") : path.join(m.dir, "index.html");
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, html);
  });

  const lessonCount = data.tracks.reduce(function (n, t) {
    return n + t.parts.reduce(function (m, p) { return m + p.lessons.length; }, 0);
  }, 0);

  console.log(`Wrote course-data.js and concept-index.js to ${path.relative(root, dataDir) || "."}${outDir ? " (--out)" : ""}`);
  console.log(`Lessons: ${lessonCount} across ${data.tracks.length} tracks; migrated: ${migrated.length}`);
}

main();
